language: python
python: 3.9

sudo: false

matrix:
  include:
    - env: ENV_FILE="envs/remake_env_3.9.yml"

install:
  # From: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html#the-travis-yml-file
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Install dependencies
  - conda env create -n remake_env --file="${ENV_FILE}"
  - conda activate remake_env
  - pip install -e .
  - conda list
  - python -c "import remake; print(remake.__version__);"
  - remake version

script:
  - nosetests --with-coverage tests

after_success:
  - codecov
