[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[project]
name = "remake"
description = "Smart remake tool"
readme = "README.md"
license = { file = "LICENCE" }
authors = [
    { name = "Mark Muetzelfeldt", email = "mark.muetzelfeldt@reading.ac.uk" },
]
maintainers = [
    { name = "Mark Muetzelfeldt", email = "mark.muetzelfeldt@reading.ac.uk" },
]
requires-python = ">=3.10"
dependencies = [
    "loguru",
    "networkx",
]
dynamic = ["version"]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Development Status :: 4 - Beta",
]

[project.urls]
Homepage = "https://github.com/markmuetz/remake"
Documentation = "https://markmuetz.github.io/remake"
"Bug Tracker" = "https://github.com/markmuetz/remake/issues"

[project.optional-dependencies]
debug = [
    "ipdb",
]
s3 = ["boto3"]
dask = [
    "distributed>=2024.8.0",
]

[dependency-groups]
dev = [
    "pytest",
    "hypothesis",
    "xarray>=2024.7.0",
    "netcdf4>=1.7.2",
    "h5netcdf>=1.8.1",
    "h5py",
    "zarr<3",
    "dask",
    "pyyaml>=6.0.3",
    "distributed>=2024.8.0",
]
docs = [
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
]

[project.scripts]
remake = "remake.remake_cmd:remake_cmd"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = { attr = "remake.version.__version__" }

[tool.pytest.ini_options]
testpaths = ["tests"]
