[build-system]
requires = ["setuptools >= 64"]
build-backend = "setuptools.build_meta"

[project]
name = "remake"
description = "Smart remake tool"
readme = "README.md"
license = { file = "LICENCE" }
authors = [
    { name = "Mark Muetzelfeldt", email = "mark.muetzelfeldt@reading.ac.uk" },
]
maintainers = [
    { name = "Mark Muetzelfeldt", email = "mark.muetzelfeldt@reading.ac.uk" },
]
requires-python = ">=3.9"
dependencies = [
    "loguru",
    "networkx",
    "pyquerylist",
    "tabulate",
]
dynamic = ["version"]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.9",
    "Development Status :: 4 - Beta",
]

[project.urls]
Homepage = "https://github.com/markmuetz/remake"
Documentation = "https://markmuetz.github.io/remake"
"Bug Tracker" = "https://github.com/markmuetz/remake/issues"

[project.optional-dependencies]
debug = ["ipdb"]

[project.scripts]
remake = "remake.remake_cmd:remake_cmd"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = { attr = "remake.version.__version__" }
